### ISSUE TITLE
Complete overhaul.

### ISSUE THREAD

**Issue by H3xadecimal** [HexadecimalPython/Xeili-DiscordBot#33]
1. Nuke redis, too much of a pain to setup and manage.
Currently looking into [TinyDB](https://tinydb.readthedocs.io) and [SQLite](https://www.sqlite.org/)

2. Refactor everything to match database changes

3. Refactor everything broken to make them not broken and fix everything so we have a base bot.

**Comment by Ovyerus** [comment]
Also rewrite to [curious](https://github.com/Fuyukai/curious) which is a Discord lib using curio which is apparently better than asyncio. ~~also might get people off my back for essentially copying ext when theres no need to~~

**Comment by H3xadecimal** [comment]
Update; after a fucking year+ later;

- Motivation.exe has stopped responding.
-  Curious has been shutdown. F.
- Other databases are garbage.
- I still haven't fixed shit bc i need to find a new goddamn DB (On the suspicions of shit breaking as i move the internal code from redis to whatever the fuck we find.)

**Comment by Ovyerus** [comment]
New database ([LevelDB](https://github.com/google/leveldb)) added in e8612da1 through 180e185. Stuff not ported to it yet.

**Comment by Ovyerus** [comment]
Fully replaced Redis with LevelDB in c622605

**Comment by H3xadecimal** [comment]
Awaiting testing; that's on me when i can be arsed to setup a linux env so as not to massively fuckup my windows one trying to get levelDB to work.

**Comment by H3xadecimal** [comment]
Tested; main bot works with a small depreciation error
`amethyst.py:34: DeprecationWarning: The object should be created from async function
  self.session = aiohttp.ClientSession()`
Commands are unresponsive, perhaps because we didn't hook up a core.

**Comment by H3xadecimal** [comment]
> Tested; main bot works with a small depreciation error
> `amethyst.py:34: DeprecationWarning: The object should be created from async function self.session = aiohttp.ClientSession()`
> Commands are unresponsive, perhaps because we didn't hook up a core.

Update; on second attempt at running more issues rose
`root@08526a482cdc:/srv/Amethyst# python amethyst.py
amethyst.py:34: DeprecationWarning: The object should be created from async function
  self.session = aiohttp.ClientSession()
Traceback (most recent call last):
  File "amethyst.py", line 90, in <module>
    amethyst = Amethyst(config)
  File "amethyst.py", line 43, in __init__
    self.db['settings']['blacklist'] = []
  File "/srv/Amethyst/utils/database.py", line 105, in __setitem__
    super().__setitem__(key, value)
  File "/usr/local/lib/python3.7/collections/__init__.py", line 1085, in __setitem__
    def __setitem__(self, i, item): self.data[i] = item
TypeError: list indices must be integers or slices, not str
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f1b77d64d68>`
Note that previous instance crashed with no warning.

**Comment by H3xadecimal** [comment]
- [ ] Stabilize the database
- [ ] Organization bots owner grabbing* 
- [ ] Return to ext
- [ ] Fix Eval's large output
- [ ] Have eval store into db instead of ram as string with a clear db function.
- [ ] Code cleanup
- [ ] redo user permission level checks.

**Comment by Ovyerus** [comment]
Database error fixed in 7e00bfc and 555d812

**Comment by H3xadecimal** [comment]
Added a few more stuff into the list

**Comment by Ovyerus** [comment]
In terms of LevelDB on windows, wbolster/plyvel#98 exists, but is still unmerged. Not sure how we'd do it ourselves unless we provided a separate script for doing the complicated shit for building it. ~~Python gets pre/post install scripts when~~

**Comment by H3xadecimal** [comment]
Updated goals.

**Comment by Ovyerus** [comment]
Probably don't need to bother about a leveldb/plyvel Windows installer due to WSL existing, and it's dead simple to get shit setup there.

**Comment by H3xadecimal** [comment]
When the fuck are we gonna debug this and make it work, it's been pending for 3 years.

**Comment by Ovyerus** [comment]
soon tm
